# Generated by Django 4.2.7 on 2023-12-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stockanalysisandprediction", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10, unique=True)),
                ("company_name", models.CharField(max_length=100)),
                ("sector", models.CharField(max_length=100)),
            ],
        ),
    ]
