# Generated by Django 4.2.7 on 2023-12-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stockanalysisandprediction", "0002_companyinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="APICache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_name", models.CharField(max_length=100)),
                ("params", models.TextField()),
                ("response", models.JSONField()),
            ],
        ),
    ]
